backend:
  name: git-gateway
  branch: master
media_folder: uploads
public_folder: /uploads
collections:
  - name: home
    label: Home
    files:
      - name: home
        label: Home
        file: index.md
        fields:
          - name: layout
            widget: hidden
            required: true
            label: Layout
            default: home
          - name: header
            widget: object
            required: false
            label: Landing Header
            hint: The text displayed above the section tabs on the landing page
            fields:
              - name: title
                widget: string
                required: true
                label: Landing Title
                hint: The title displayed on the landing page
              - name: subtitle
                widget: markdown
                required: false
                label: Landing Subtitle
                hint: The text displayed below the landing page title
          - name: sections
            widget: list
            required: false
            label: Sections
            hint: Home Sections
            types:
              - name: section_simple
                widget: object
                label: Generic Section
                fields:
                  - name: title
                    widget: string
                    required: true
                    label: Section Title
                    default: Intro
                    hint: The title of the section
                  - name: element_id
                    widget: string
                    required: true
                    label: Section ID
                    default: intro
                    hint: The ID of the section
                  - name: image_url
                    widget: image
                    required: false
                    label: Image
                    hint: Image displayed above section content
                  - name: image_alt
                    widget: string
                    required: false
                    label: Image Alternate Text
                  - name: content
                    widget: markdown
                    required: false
                    label: Section Content
                  - name: component
                    widget: hidden
                    required: true
                    label: Section Component
                    default: section_simple.html
              - name: section_contact
                widget: object
                label: Contact Section
                fields:
                  - name: title
                    widget: string
                    required: true
                    label: Section Title
                    default: Contact
                    hint: The title of the section
                  - name: element_id
                    widget: string
                    required: true
                    label: Section ID
                    default: contact
                    hint: The ID of the section
                  - name: component
                    widget: hidden
                    required: true
                    label: Section Component
                    default: section_contact.html
              - name: section_elements
                widget: object
                label: Elements Section
                fields:
                  - name: title
                    widget: string
                    required: true
                    label: Section Title
                    default: Elements
                    hint: The title of the section
                  - name: element_id
                    widget: string
                    required: true
                    label: Section ID
                    default: elements
                    hint: The ID of the section
                  - name: component
                    widget: hidden
                    required: true
                    label: Section Component
                    default: section_elements.html
